Modify certain data points in the dataset for target reaching experiment.

In [110]:
import os
import numpy as np
import path_settings

In [111]:
data_alias = 'D' + str(0).zfill(2)
data_save_path = os.path.join(path_settings.target_parameters_dir, data_alias + '.npy')
print(data_save_path)
data = np.load(data_save_path)

E:/OneDrive - UC San Diego/UCSD/Lab/Catheter/diff_catheter/data/target_parameters\D00.npy


In [112]:
print(path_settings.target_parameters_dir)

E:/OneDrive - UC San Diego/UCSD/Lab/Catheter/diff_catheter/data/target_parameters


In [113]:
target_parameters_dir_new = "E:/OneDrive - UC San Diego/UCSD/Lab/Catheter/diff_catheter/data/target_parameters_new"
print(target_parameters_dir_new)

E:/OneDrive - UC San Diego/UCSD/Lab/Catheter/diff_catheter/data/target_parameters_new


In [114]:
data_save_path_new = os.path.join(target_parameters_dir_new, data_alias + '.npy')
print(data_save_path_new)
data_new = np.load(data_save_path_new)

E:/OneDrive - UC San Diego/UCSD/Lab/Catheter/diff_catheter/data/target_parameters_new\D00.npy


In [115]:
print(data)

[[ 1.03185628e-03  8.76170642e-04  2.00000000e-01]
 [ 6.91127395e-04  8.60013006e-05  2.00000000e-01]
 [-1.11982765e-03 -8.55820117e-04  2.00000000e-01]
 [-1.27343989e-04  6.14049256e-04  2.00000000e-01]
 [ 1.90037287e-04 -5.14557144e-04  2.00000000e-01]
 [-9.13737788e-04 -8.27745202e-04  2.00000000e-01]
 [-2.73344238e-04 -8.48925992e-04  2.00000000e-01]
 [-6.51563174e-04  5.70540644e-04  2.00000000e-01]
 [ 4.88772611e-04 -7.61207694e-04  2.00000000e-01]
 [ 3.78704557e-04  5.45598516e-04  2.00000000e-01]
 [ 1.27815147e-03 -3.01028774e-05  2.00000000e-01]
 [-2.62750691e-04  2.16927389e-04  2.00000000e-01]
 [-4.35241476e-04  5.40526565e-04  2.00000000e-01]
 [-6.39646631e-04 -2.88660274e-04  2.00000000e-01]
 [ 1.11604600e-03 -2.54492918e-04  2.00000000e-01]
 [-4.73714443e-04  8.42528991e-04  2.00000000e-01]
 [ 6.79512228e-05 -4.44751975e-04  2.00000000e-01]
 [ 2.22218269e-05 -1.33219418e-04  2.00000000e-01]
 [-1.19850609e-03  3.72021501e-04  2.00000000e-01]
 [ 7.05042042e-04  2.07009619e-

In [116]:
print(data_new)

[[0.0006772  0.00095415 0.2       ]
 [0.00079626 0.00088101 0.2       ]
 [0.0007752  0.00053533 0.2       ]
 [0.00074987 0.0006617  0.2       ]
 [0.00083903 0.00070088 0.2       ]
 [0.00109505 0.00059247 0.2       ]
 [0.00052891 0.0006853  0.2       ]
 [0.00103156 0.00086665 0.2       ]
 [0.00118047 0.00059894 0.2       ]
 [0.00061054 0.00070233 0.2       ]
 [0.00125742 0.0008532  0.2       ]
 [0.00119307 0.00052213 0.2       ]
 [0.0009389  0.00052315 0.2       ]
 [0.00088683 0.00055244 0.2       ]
 [0.00068404 0.00056671 0.2       ]
 [0.00101765 0.00076424 0.2       ]
 [0.00099171 0.00064041 0.2       ]
 [0.000761   0.00064893 0.2       ]
 [0.00136434 0.00082268 0.2       ]
 [0.00092261 0.00086827 0.2       ]
 [0.00057572 0.00071949 0.2       ]
 [0.00103468 0.00060889 0.2       ]
 [0.00111732 0.00054721 0.2       ]
 [0.00117616 0.00054165 0.2       ]
 [0.00059869 0.00071712 0.2       ]
 [0.00071575 0.00075279 0.2       ]
 [0.0013386  0.00072156 0.2       ]
 [0.00056051 0.00060427 0.2 

In [117]:
print(data[25, :])
print(data_new[25, :])

[-1.06952363e-03 -1.93582935e-06  2.00000000e-01]
[0.00071575 0.00075279 0.2       ]


In [118]:
data[25, :] = data_new[25, :]
data[98, :] = data_new[98, :]

In [119]:
np.save(data_save_path, data)
