In [3]:
import numpy as np

P = np.array([
    [1/2, 1/4, 0,   0,   1/4],
    [1/4, 1/2, 1/4, 0,   0],
    [0,   1/4, 1/2, 1/4, 0],
    [0,   0,   1/4, 1/2, 1/4],
    [1/4, 0,   0,   1/4, 1/2]
])

P_100 = np.linalg.matrix_power(P, 100)

print(P_100)

P0 = np.array([[25/150, 20/150, 35/150, 24/150, 46/150]]).T

result = P0.T @ P_100

print(result)


[[0.2 0.2 0.2 0.2 0.2]
 [0.2 0.2 0.2 0.2 0.2]
 [0.2 0.2 0.2 0.2 0.2]
 [0.2 0.2 0.2 0.2 0.2]
 [0.2 0.2 0.2 0.2 0.2]]
[[0.2 0.2 0.2 0.2 0.2]]


In [1]:
from sympy import Matrix, symbols

# Define the matrix A1
A1 = Matrix([
    [1, 1, 0],
    [0, 1, 0],
    [0, 0, 1]
])

# Calculate the characteristic polynomial of the matrix A1
lambda_symbol = symbols('lambda')
char_poly_A1 = A1.charpoly(lambda_symbol)

char_poly_A1


PurePoly(lambda**3 - 3*lambda**2 + 3*lambda - 1, lambda, domain='ZZ')

In [4]:
from sympy import symbols, Matrix, exp

# 定义时间变量
t = symbols('t')

# 定义矩阵 A1
A1 = Matrix([
    [2, 0, 0, 0],
    [2, 2, 0, 0],
    [0, 0, 3, 3],
    [0, 0, 0, 3]
])

# 计算矩阵指数 e^(A1*t)
exp_A1_t = exp(A1 * t)

# 展示结果
exp_A1_t


Matrix([
[    exp(2*t),        0,        0,            0],
[2*t*exp(2*t), exp(2*t),        0,            0],
[           0,        0, exp(3*t), 3*t*exp(3*t)],
[           0,        0,        0,     exp(3*t)]])