In [15]:
import numpy as np

In [16]:
case_naming = 'E:/OneDrive - UC San Diego/UCSD/Lab/Catheter/diff_catheter/scripts/test_diff_render_catheter_v2/gt_dataset/gt_4_0.0006_0.0005_0.2_0.01'
img_save_path = case_naming + '.png'
cc_specs_path = case_naming + '.npy'

para_gt_np = np.load(cc_specs_path)

print(para_gt_np)
print(para_gt_np.shape)

matrix = np.squeeze(para_gt_np)

# Extract vectors r2 and r4
c1 = matrix[2]
p_end = matrix[1]

# Compute vector r
p_mid = 3/4 * (c1 + p_end/3)

# Concatenate vectors r and r4 to form a new vector of length 6
result_vector = np.concatenate((p_mid, p_end))

print(result_vector)


[[[0.02       0.002      0.        ]
  [0.16714074 0.12461728 0.98111248]
  [0.02047046 0.00239205 0.33970698]
  [0.06951738 0.04326448 0.66674447]]]
(1, 4, 3)
[0.05713803 0.03294836 0.50005836 0.16714074 0.12461728 0.98111248]


In [17]:
def read_gt_params(cc_specs_path):
    """
    The order of gt: [p_start, p_end, c1, c2]
    """
    
    para_gt_np = np.load(cc_specs_path)
    matrix = np.squeeze(para_gt_np)
    c1 = matrix[2]
    p_end = matrix[1]
    p_mid = 3/4 * (c1 + p_end/3)
    result_vector = np.concatenate((p_mid, p_end))
    return result_vector   

In [18]:
case_naming = 'E:/OneDrive - UC San Diego/UCSD/Lab/Catheter/diff_catheter/data/rendered_images/dof2_64/dof2_c48_0.001_-0.005_0.2_0.01'
img_save_path = case_naming + '.png'
cc_specs_path = case_naming + '_gt.npy'
para_gt_np = np.load(cc_specs_path)

print(para_gt_np)
print(para_gt_np[1:3, :].flatten())


[[ 0.02        0.002       0.        ]
 [ 0.02007997  0.00160014  0.1026283 ]
 [ 0.02973628 -0.04668138  0.19240253]]
[ 0.02007997  0.00160014  0.1026283   0.02973628 -0.04668138  0.19240253]
